// ═══════════════════════════════════════════════════════════════
//  RANKD — FICHIER DE QUESTIONS
//  Modifie ce fichier pour ajouter ou changer des questions.
//
//  FORMAT :
//  { text: "La question ?", emoji: "😄" },
//
//  RÈGLES :
//  - Chaque thème peut avoir autant de questions que tu veux
//  - Plus tu en ajoutes, moins elles se répètent
//  - L'emoji est optionnel (mets "❓" si t'as pas d'idée)
// ═══════════════════════════════════════════════════════════════

const RANKD_QUESTIONS = {

  // ── 🤝 POTES ────────────────────────────────────────────────
  potes: [
    { text: "Qui pleure le plus souvent ?", emoji: "😭" },
    { text: "Qui oublie l'anniversaire de tout le monde ?", emoji: "🎂" },
    { text: "Qui aime encore son ex ?", emoji: "📱" },
    { text: "Qui mange le plus salement ?", emoji: "🍕" },
    { text: "Qui est le plus perché ?", emoji: "🗺️" },
    { text: "Qui est le dernier à comprendre une blague ?", emoji: "😶" },
    { text: "Qui deviendra riche en premier ?", emoji: "💰" },
    { text: "Qui est le plus extraverti ?", emoji: "🚇" },
    { text: "Qui va habiter dans un cabane ?", emoji: "🏠" },
    { text: "Qui se ferait arnaquer par un scammer ?", emoji: "🎣" },
    { text: "Qui est le dernier à admettre qu'il a tort ?", emoji: "🤬" },
    { text: "Qui envoie des vocaux toujours trop longs ?", emoji: "🎙️" },
    { text: "Qui gagnerait un concours de mauvaises blagues ?", emoji: "🥲" },
    { text: "Qui filme dans toutes les situations ?", emoji: "📸" },
    { text: "Qui est le plus courageux pour aborder ?", emoji: "💘" },
    { text: "Qui est le plus sportif ?", emoji: "🍰" },
    { text: "Qui n'a jamais de batterie sur son tél ?", emoji: "🔋" },
    { text: "Qui est le plus actif en soirée ?", emoji: "🎤" },
    { text: "Qui se lève le plus tard le week-end ?", emoji: "😴" },
    { text: "Qui est le plus depensier ?", emoji: "💸" },
    { text: "Qui serait le meilleur avocat si sa vie en dépendait ?", emoji: "⚖️" },
    { text: "Qui est le plus facilement manipulable ?", emoji: "🎭" },
    { text: "Qui cuisine le mieux ?", emoji: "👨‍🍳" },
    { text: "Qui disparaîtrait le plus souvent pendant une soirée ?", emoji: "👻" },
    { text: "Qui fait les meilleurs discours improvisés ?", emoji: "💍" },
    { text: "Qui n'aura jamais le permis ?", emoji: "🧭" },   
    { text: "Qui est le plus fou ?", emoji: "💡" },
    { text: "Qui arrivera en retard à son propre mariage ?", emoji: "💒" },
    { text: "Qui serait le meilleur DJ d'une soirée ?", emoji: "🎧" },
    { text: "Qui deviendra le plus célèbre du groupe ?", emoji: "🌟" },
    { text: "Qui aura le plus de tatouages dans plus tard ?", emoji: "💉" },
    { text: "Qui partirait vivre à l'étranger ?", emoji: "✈️" },
    { text: "Qui est le plus accro a son tél ?", emoji: "📲" },
    { text: "Qui abuse le plus de la boisson en soirée ?", emoji: "🏆" },
    { text: "Qui est le premier à s'endormir en soirée ?", emoji: "🎬" },
    { text: "Qui à le plus de mal à garder un secret ?", emoji: "🤭" },
    { text: "Qui est le plus gros daleux ?", emoji: "🎈" },
    { text: "Qui serait le plus susceptible de se faire dm sur insta ?", emoji: "💬" },
    { text: "Qui serait le premier à pleurer de rire ?", emoji: "😂" },
    { text: "Qui se réconcilie le plus vite après une dispute ?", emoji: "🤝" },
    { text: "Qui est le plus difficile à réveiller le matin ?", emoji: "🛌" },
  ],

  // ── 🎉 SOIRÉE ───────────────────────────────────────────────
  soiree: [
    { text: "Qui serait le premier sur la piste de danse ?", emoji: "🕺" },
    { text: "Qui commanderait à manger à 3h du matin ?", emoji: "🍕" },
    { text: "Qui tomberait endormi en premier ?", emoji: "😴" },
    { text: "Qui ferait le speech le plus embarrassant ?", emoji: "🎤" },
    { text: "Qui serait le dernier à rentrer chez lui ?", emoji: "🌅" },
    { text: "Qui danserait seul dans un coin sans s'en rendre compte ?", emoji: "💃" },
    { text: "Qui perdrait ses affaires en premier ?", emoji: "👜" },
    { text: "Qui aurait la pire gueule de bois le lendemain ?", emoji: "🤢" },
    { text: "Qui se ferait des amis avec tout le monde en 5 minutes ?", emoji: "🤗" },
    { text: "Qui appellerait son ex pendant la soirée ?", emoji: "📞" },
    { text: "Qui prendrait le plus de selfies de la nuit ?", emoji: "🤳" },
    { text: "Qui serait le dernier à quitter la piste ?", emoji: "🎉" },
    { text: "Qui ferait la danse la plus mémorable ?", emoji: "🎵" },
    { text: "Qui essaierait de devenir ami avec le videur ?", emoji: "🚪" },
    { text: "Qui organiserait l'after party spontanément ?", emoji: "🏠" },
    { text: "Qui chanterait le plus fort sur une chanson qu'il connaît pas ?", emoji: "🎶" },
    { text: "Qui porterait la tenue la plus remarquée ?", emoji: "👗" },
    { text: "Qui monterait sur une table ?", emoji: "🪑" },
    { text: "Qui raterait son taxi et dormirait sur place ?", emoji: "🚕" },
    { text: "Qui ferait la meilleure photo souvenir ?", emoji: "📷" },
    { text: "Qui chanterait a capella sans qu'on lui demande ?", emoji: "🎤" },
    { text: "Qui parlerait le plus fort de tout le monde ?", emoji: "📢" },
    { text: "Qui commanderait le cocktail le plus bizarre ?", emoji: "🍹" },
    { text: "Qui resterait le plus sobre de la nuit ?", emoji: "💧" },
    { text: "Qui posterait le plus de stories ?", emoji: "📱" },
    { text: "Qui proposerait de continuer ailleurs à minuit ?", emoji: "🌃" },
    { text: "Qui proposerait un jeu en premier ?", emoji: "🎮" },
    { text: "Qui ferait la meilleure imitation de quelqu'un ?", emoji: "🎭" },
    { text: "Qui aurait la meilleure playlist ?", emoji: "🎵" },
    { text: "Qui ramènerait des inconnus dans le groupe ?", emoji: "👥" },
    { text: "Qui perdrait le fil de la conversation le plus vite ?", emoji: "💭" },
    { text: "Qui ne retrouverait pas son téléphone de la nuit ?", emoji: "📵" },
    { text: "Qui dépenserait le plus en une nuit ?", emoji: "💸" },
    { text: "Qui finirait dans un after inattendu ?", emoji: "🎊" },
    { text: "Qui ferait rire tout le monde avec ses danses ?", emoji: "😂" },
    { text: "Qui serait le roi ou la reine de la soirée ?", emoji: "👑" },
    { text: "Qui s'endormirait sur le canapé en premier ?", emoji: "🛋️" },
    { text: "Qui rentrerait avec le plus de nouvelles connaissances ?", emoji: "📲" },
    { text: "Qui perdrait ses chaussures en premier ?", emoji: "👠" },
    { text: "Qui commanderait pour tout le monde sans demander ?", emoji: "📋" },
    { text: "Qui organiserait la prochaine soirée sur le chemin du retour ?", emoji: "📅" },
    { text: "Qui danserait le plus mal mais avec le plus de confiance ?", emoji: "🕺" },
    { text: "Qui ferait semblant d'être occupé pour éviter quelqu'un ?", emoji: "🙈" },
    { text: "Qui s'endormirait dans le taxi ?", emoji: "🚗" },
    { text: "Qui dépenserait le plus en Uber sur la nuit ?", emoji: "🚖" },
    { text: "Qui serait le plus susceptible de perdre sa veste ?", emoji: "🧥" },
    { text: "Qui ferait le toast le plus mémorable ?", emoji: "🥂" },
    { text: "Qui viderait le buffet en premier ?", emoji: "🍽️" },
    { text: "Qui serait le premier à proposer une photo de groupe ?", emoji: "📸" },
    { text: "Qui finirait la nuit à raconter sa vie à des inconnus ?", emoji: "🗣️" },
    { text: "Qui serait le plus susceptible de perdre ses clés en rentrant ?", emoji: "🔑" },
    { text: "Qui serait encore debout à 7h du matin ?", emoji: "☀️" },
    { text: "Qui enverrait le message le plus gênant de la nuit ?", emoji: "😬" },
    { text: "Qui serait le plus susceptible de pleurer sans raison apparente ?", emoji: "😭" },
    { text: "Qui serait le premier à proposer de quitter la fête trop tôt ?", emoji: "🏃" },
    { text: "Qui serait le plus susceptible de raconter un secret ce soir ?", emoji: "🤫" },
    { text: "Qui prendrait le plus de place sur la piste ?", emoji: "💥" },
    { text: "Qui ferait un discours non sollicité au micro ?", emoji: "🎙️" },
    { text: "Qui serait le plus susceptible de retrouver un ami perdu de vue ?", emoji: "🫂" },
    { text: "Qui enverrait le plus de messages à son crush cette nuit ?", emoji: "💌" },
    { text: "Qui serait le dernier à se souvenir de ce qui s'est passé le lendemain ?", emoji: "🤔" },
  ],

  // ── 💕 AMOUREUX ─────────────────────────────────────────────
  amoureux: [
    { text: "Qui enverrait le premier message après un silence gêné ?", emoji: "💬" },
    { text: "Qui tomberait amoureux le plus vite ?", emoji: "❤️" },
    { text: "Qui serait le plus jaloux dans une relation ?", emoji: "😤" },
    { text: "Qui serait le plus romantique du groupe ?", emoji: "🌹" },
    { text: "Qui préparerait la meilleure surprise pour son partenaire ?", emoji: "🎁" },
    { text: "Qui lirait tous les messages de son crush en détail ?", emoji: "🔍" },
    { text: "Qui attendrait le plus longtemps avant de déclarer ses sentiments ?", emoji: "⏳" },
    { text: "Qui ferait un geste romantique en public ?", emoji: "💏" },
    { text: "Qui regarderait des films romantiques en cachette ?", emoji: "🎬" },
    { text: "Qui ferait la meilleure première impression ?", emoji: "✨" },
    { text: "Qui serait le plus difficile à reconquérir après une dispute ?", emoji: "🌧️" },
    { text: "Qui céderait le premier dans une dispute de couple ?", emoji: "🏳️" },
    { text: "Qui ferait le plus de sacrifices pour l'amour ?", emoji: "💝" },
    { text: "Qui aurait le coup de foudre le plus facilement ?", emoji: "⚡" },
    { text: "Qui planterait un rendez-vous pour regarder Netflix ?", emoji: "🛋️" },
    { text: "Qui serait le plus attentionné dans une relation ?", emoji: "🫶" },
    { text: "Qui dirait je t'aime en premier ?", emoji: "💕" },
    { text: "Qui ferait le plus long trajet pour voir quelqu'un ?", emoji: "🚂" },
    { text: "Qui serait le plus difficile à impressionner ?", emoji: "😏" },
    { text: "Qui se souviendrait de tous les anniversaires de couple ?", emoji: "📅" },
    { text: "Qui garderait un secret amoureux le mieux ?", emoji: "🤫" },
    { text: "Qui enverrait des fleurs sans raison particulière ?", emoji: "💐" },
    { text: "Qui relirait les vieilles conversations avec son crush ?", emoji: "💭" },
    { text: "Qui ferait le dîner romantique parfait ?", emoji: "🍷" },
    { text: "Qui écrirait une lettre à la main ?", emoji: "✍️" },
    { text: "Qui serait le plus difficile à lire quand il a des sentiments ?", emoji: "🎭" },
    { text: "Qui ferait le meilleur câlin du groupe ?", emoji: "🤗" },
    { text: "Qui stalkerait son crush sur les réseaux ?", emoji: "👀" },
    { text: "Qui donnerait toujours la priorité à l'amour sur l'amitié ?", emoji: "💔" },
    { text: "Qui tomberait amoureux d'un inconnu en voyage ?", emoji: "🌍" },
    { text: "Qui serait le plus loyal dans une longue relation ?", emoji: "💍" },
    { text: "Qui ferait le plus beau discours d'anniversaire ?", emoji: "🎂" },
    { text: "Qui consolerait le mieux son partenaire ?", emoji: "🤍" },
    { text: "Qui ferait une surprise à minuit ?", emoji: "🎆" },
    { text: "Qui remarquerait un changement chez son partenaire en premier ?", emoji: "🔎" },
    { text: "Qui garderait toutes les photos de couple ?", emoji: "🖼️" },
    { text: "Qui ferait le geste le plus inattendu pour plaire ?", emoji: "🎯" },
    { text: "Qui présenterait son partenaire à la famille en premier ?", emoji: "👨‍👩‍👦" },
    { text: "Qui tomberait amoureux d'un ami ?", emoji: "🫂" },
    { text: "Qui serait le plus attentif aux détails chez son partenaire ?", emoji: "🌸" },
    { text: "Qui organiserait le voyage romantique parfait ?", emoji: "🏖️" },
    { text: "Qui resterait avec quelqu'un qui ne le mérite pas ?", emoji: "😔" },
    { text: "Qui ferait rire son partenaire dans les moments difficiles ?", emoji: "😄" },
    { text: "Qui ferait la demande en mariage la plus créative ?", emoji: "💍" },
    { text: "Qui serait le plus dépendant affectivement ?", emoji: "🔗" },
    { text: "Qui s'excuserait en premier après une dispute ?", emoji: "🙏" },
    { text: "Qui vivrait la plus belle histoire d'amour du groupe ?", emoji: "📖" },
    { text: "Qui enverrait le message le plus long à son crush ?", emoji: "📝" },
    { text: "Qui ferait la playlist parfaite pour une soirée en amoureux ?", emoji: "🎵" },
    { text: "Qui serait le plus susceptible de tomber amoureux d'une célébrité ?", emoji: "🌟" },
    { text: "Qui organiserait la Saint-Valentin parfaite ?", emoji: "💝" },
    { text: "Qui serait le plus susceptible de faire le premier pas ?", emoji: "🦁" },
    { text: "Qui serait le plus jaloux d'un like d'un inconnu ?", emoji: "😒" },
    { text: "Qui serait le plus susceptible de déménager pour l'amour ?", emoji: "📦" },
    { text: "Qui lirait les horoscopes de compatibilité ?", emoji: "♈" },
    { text: "Qui serait le plus susceptible de faire une sérénade ?", emoji: "🎸" },
    { text: "Qui écrirait une chanson pour son crush ?", emoji: "🎼" },
    { text: "Qui serait le plus susceptible de tomber amoureux au premier regard ?", emoji: "👁️" },
    { text: "Qui garderait tous les tickets de leurs sorties en couple ?", emoji: "🎟️" },
    { text: "Qui serait le plus susceptible de faire une déclaration devant tout le monde ?", emoji: "📣" },
    { text: "Qui planterait quelqu'un pour rester avec son partenaire ?", emoji: "🙈" },
  ],

  // ── 👨‍👩‍👧‍👦 FAMILLE ──────────────────────────────────────────────
  famille: [
    { text: "Qui est le chouchou des grands-parents ?", emoji: "👴" },
    { text: "Qui appellerait sa mère tous les jours ?", emoji: "📞" },
    { text: "Qui arriverait en retard à tous les repas de famille ?", emoji: "🍽️" },
    { text: "Qui donnerait les meilleurs conseils dans la famille ?", emoji: "🧠" },
    { text: "Qui se marierait en premier ?", emoji: "👰" },
    { text: "Qui ferait pleurer tout le monde à Noël avec son discours ?", emoji: "🎄" },
    { text: "Qui ramènerait un inconnu au repas de famille ?", emoji: "🚶" },
    { text: "Qui défendrait toujours les autres même quand ils ont tort ?", emoji: "🛡️" },
    { text: "Qui serait le plus nostalgique des vacances d'enfance ?", emoji: "🏖️" },
    { text: "Qui ressemblerait le plus à ses parents en vieillissant ?", emoji: "👨‍👩‍👦" },
    { text: "Qui serait le meilleur pour garder les enfants ?", emoji: "👶" },
    { text: "Qui cuisinerait le meilleur repas de Noël ?", emoji: "🎅" },
    { text: "Qui aurait des enfants en premier ?", emoji: "🍼" },
    { text: "Qui garderait toutes les traditions familiales ?", emoji: "🏠" },
    { text: "Qui déménagerait le plus loin de sa famille ?", emoji: "✈️" },
    { text: "Qui raconterait tout à ses parents ?", emoji: "🗣️" },
    { text: "Qui offrirait les meilleurs cadeaux à Noël ?", emoji: "🎁" },
    { text: "Qui jouerait le médiateur lors des disputes familiales ?", emoji: "🤝" },
    { text: "Qui ferait honte à toute la famille au karaoké du réveillon ?", emoji: "🎤" },
    { text: "Qui pleurerait en regardant les vieilles photos de famille ?", emoji: "📷" },
    { text: "Qui serait le dernier à quitter la maison familiale ?", emoji: "🏡" },
    { text: "Qui deviendrait comme son parent préféré ?", emoji: "💛" },
    { text: "Qui organiserait les meilleures retrouvailles familiales ?", emoji: "🎊" },
    { text: "Qui garderait le plus de secrets de famille ?", emoji: "🤫" },
    { text: "Qui vivrait dans la même ville que ses parents ?", emoji: "📍" },
    { text: "Qui aiderait le plus lors d'un déménagement familial ?", emoji: "📦" },
    { text: "Qui ferait la plus longue route pour les fêtes ?", emoji: "🚗" },
    { text: "Qui oublierait d'appeler pour un anniversaire ?", emoji: "🎂" },
    { text: "Qui serait le plus proche de ses cousins ?", emoji: "👫" },
    { text: "Qui hériterait des meilleures recettes de famille ?", emoji: "📖" },
    { text: "Qui prendrait soin de ses parents quand ils seront vieux ?", emoji: "❤️" },
    { text: "Qui ferait le meilleur barbecue familial ?", emoji: "🔥" },
    { text: "Qui serait le pilier de la famille ?", emoji: "🏛️" },
    { text: "Qui réconcilierait les membres en froid ?", emoji: "🕊️" },
    { text: "Qui raconterait les meilleures anecdotes de famille ?", emoji: "📚" },
    { text: "Qui ferait le plus rire lors des repas de famille ?", emoji: "😂" },
    { text: "Qui transmettrait le mieux les valeurs familiales ?", emoji: "🌱" },
    { text: "Qui arriverait en premier en cas de problème familial ?", emoji: "🏃" },
    { text: "Qui garderait le contact avec toute la famille ?", emoji: "🌐" },
    { text: "Qui serait le plus attaché aux souvenirs de famille ?", emoji: "🏺" },
    { text: "Qui créerait le groupe WhatsApp familial ?", emoji: "💬" },
    { text: "Qui serait le meilleur parrain ou marraine ?", emoji: "✨" },
    { text: "Qui serait le plus fier de ses racines familiales ?", emoji: "🌿" },
    { text: "Qui viderait le frigo de ses parents en rentrant ?", emoji: "🍽️" },
    { text: "Qui ferait fondre les grands-parents avec un seul sourire ?", emoji: "😊" },
    { text: "Qui pleurerait le plus à un mariage de famille ?", emoji: "😭" },
    { text: "Qui organiserait la meilleure fête d'anniversaire pour un parent ?", emoji: "🎉" },
    { text: "Qui serait le premier à appeler tout le monde pour des nouvelles ?", emoji: "📲" },
    { text: "Qui préparerait le meilleur repas de fête ?", emoji: "🍗" },
    { text: "Qui ferait les meilleures photos aux réunions de famille ?", emoji: "📸" },
    { text: "Qui serait le plus susceptible de pleurer à la remise de diplôme ?", emoji: "🎓" },
    { text: "Qui serait le plus susceptible de répéter les mêmes histoires que ses grands-parents ?", emoji: "📜" },
    { text: "Qui serait le premier à se réconcilier après une dispute familiale ?", emoji: "🤗" },
    { text: "Qui serait le plus susceptible de garder tous les dessins d'enfance ?", emoji: "🎨" },
    { text: "Qui ferait la meilleure imitation d'un parent ?", emoji: "🎭" },
    { text: "Qui serait le plus susceptible de citer ses parents dans une conversation ?", emoji: "💬" },
    { text: "Qui préparerait la meilleure surprise pour un anniversaire de famille ?", emoji: "🎁" },
    { text: "Qui serait le plus susceptible de garder les vieilles photos de famille ?", emoji: "🖼️" },
    { text: "Qui serait le premier à proposer une réunion de famille ?", emoji: "📅" },
    { text: "Qui serait le plus susceptible de pleurer en regardant les vidéos d'enfance ?", emoji: "🎥" },
    { text: "Qui serait le plus susceptible de tout faire pour rendre la famille fière ?", emoji: "🏆" },
  ],

};

// Ne modifie pas cette ligne — elle permet au jeu de lire le fichier
if (typeof window !== 'undefined') window.RANKD_QUESTIONS = RANKD_QUESTIONS;
